name: "Docs fix/update"
description: Corrections or additions to documentation
title: "docs: <area>"
labels: ["docs"]
body:
  - type: input
    id: url
    attributes:
      label: Doc URL or path
      placeholder: "docs/<path> or https://docs.neus.network/<...>"
    validations: { required: true }
  - type: textarea
    id: change
    attributes:
      label: Proposed change
      placeholder: "What’s wrong and the exact fix?"
    validations: { required: true }

